//==============================================================================
// File      : clk_reset_gen.v
// Author    : Open-Source Example
// Version   : 1.0
// SPDX-License-Identifier: Apache-2.0
// Description: Simple clock and reset generator mock-up
//==============================================================================
module clk_reset_gen
#(
    parameter integer CLK_MUL = 2,  // Example PLL multiplier
    parameter integer CLK_DIV = 1   // Example PLL divider
)
(
    input  wire clk_in,
    input  wire reset_in,
    output wire clk_out,
    output wire locked,   // Indicates PLL has locked onto the new frequency
    output wire reset_out // Synchronized reset
);

    //--------------------------------------------------------------------------
    // PLL/Clock Generation (Mock)
    //--------------------------------------------------------------------------
    // In a real design, you'd instantiate a PLL or clock block from your 
    // technology library or use an open-source PLL wrapper. Below is a placeholder:
    reg pll_lock_reg;
    assign locked = pll_lock_reg;

    always @(posedge clk_in or posedge reset_in) begin
        if (reset_in) begin
            pll_lock_reg <= 1'b0;
        end else begin
            // This is a simplistic representation of PLL lock
            pll_lock_reg <= 1'b1;
        end
    end

    // Create an internal clock domain to represent the multiplied/divided clock
    // In real hardware, this is generated by the PLL. Here we just create a 
    // toggling clock for demonstration.
    reg clk_div_reg;
    assign clk_out = clk_div_reg;

    integer counter;
    always @(posedge clk_in or posedge reset_in) begin
        if (reset_in) begin
            clk_div_reg <= 1'b0;
            counter     <= 0;
        end else if (pll_lock_reg == 1'b1) begin
            if (counter == ((CLK_DIV * 2 / CLK_MUL) - 1)) begin
                clk_div_reg <= ~clk_div_reg;
                counter     <= 0;
            end else begin
                counter <= counter + 1;
            end
        end
    end

    //--------------------------------------------------------------------------
    // Reset Synchronization
    //--------------------------------------------------------------------------
    reg [1:0] reset_sync;
    always @(posedge clk_out or negedge pll_lock_reg) begin
        if (!pll_lock_reg) begin
            reset_sync <= 2'b11;
        end else begin
            reset_sync <= {reset_sync[0], 1'b0};
        end
    end

    assign reset_out = reset_sync[1];

endmodule
