name: dashcam-soc-mock-ci
on:
  push:
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator make python3 gcc
      - name: Generate regs
        run: make regs
      - name: Build firmware
        run: make sw
      - name: Smoke sim
        run: make sim
