#ifndef DASHCAM_REGS_H
#define DASHCAM_REGS_H
#define DASHCAM_CSR_BASE 0x10000000u

#define REG_CTRL (DASHCAM_CSR_BASE + 0x00u)
#define REG_CAM_STATUS (DASHCAM_CSR_BASE + 0x04u)
#define REG_DMA_BASE (DASHCAM_CSR_BASE + 0x08u)
#define REG_DMA_LEN (DASHCAM_CSR_BASE + 0x0cu)
#define REG_DMA_STATUS (DASHCAM_CSR_BASE + 0x10u)
#define REG_IRQ_STATUS (DASHCAM_CSR_BASE + 0x14u)
#define REG_IRQ_CLEAR (DASHCAM_CSR_BASE + 0x18u)
#define REG_IOMUX_SEL (DASHCAM_CSR_BASE + 0x1cu)
#define REG_SD_STATUS (DASHCAM_CSR_BASE + 0x20u)
#define REG_BUILD_INFO (DASHCAM_CSR_BASE + 0x24u)

#endif
